"""Tests for private generated-CV artifact storage."""

from pathlib import Path

import pytest

from careerops_agent_engine.domain.enums import (
    CVArtifactFormat,
)
from careerops_agent_engine.infrastructure.storage.local_artifact_storage import (
    LocalArtifactStorage,
)


def test_save_and_read_artifact(
    tmp_path: Path,
) -> None:
    """Generated bytes should round-trip inside the owner namespace."""

    storage = LocalArtifactStorage(
        tmp_path
    )

    result = storage.save(
        user_id="USER-001",
        cv_version_id="CVV-001",
        artifact_id="ART-001",
        artifact_format=CVArtifactFormat.DOCX,
        data=b"docx-bytes",
    )

    assert result.created is True

    assert storage.read(
        user_id="USER-001",
        storage_key=result.storage_key,
    ) == b"docx-bytes"


def test_exact_storage_retry_is_idempotent(
    tmp_path: Path,
) -> None:
    """Writing identical immutable bytes again should be harmless."""

    storage = LocalArtifactStorage(
        tmp_path
    )

    first = storage.save(
        user_id="USER-001",
        cv_version_id="CVV-001",
        artifact_id="ART-001",
        artifact_format=CVArtifactFormat.DOCX,
        data=b"same-bytes",
    )

    second = storage.save(
        user_id="USER-001",
        cv_version_id="CVV-001",
        artifact_id="ART-001",
        artifact_format=CVArtifactFormat.DOCX,
        data=b"same-bytes",
    )

    assert first.storage_key == (
        second.storage_key
    )

    assert first.created is True
    assert second.created is False


def test_same_storage_identity_cannot_change_bytes(
    tmp_path: Path,
) -> None:
    """An existing generated artifact cannot silently mutate."""

    storage = LocalArtifactStorage(
        tmp_path
    )

    storage.save(
        user_id="USER-001",
        cv_version_id="CVV-001",
        artifact_id="ART-001",
        artifact_format=CVArtifactFormat.DOCX,
        data=b"first",
    )

    with pytest.raises(
        FileExistsError,
        match="different bytes",
    ):
        storage.save(
            user_id="USER-001",
            cv_version_id="CVV-001",
            artifact_id="ART-001",
            artifact_format=CVArtifactFormat.DOCX,
            data=b"changed",
        )


def test_cross_user_read_is_blocked(
    tmp_path: Path,
) -> None:
    """Opaque keys must remain bound to their authenticated owner."""

    storage = LocalArtifactStorage(
        tmp_path
    )

    result = storage.save(
        user_id="USER-001",
        cv_version_id="CVV-001",
        artifact_id="ART-001",
        artifact_format=CVArtifactFormat.DOCX,
        data=b"private",
    )

    with pytest.raises(
        FileNotFoundError,
        match="unavailable",
    ):
        storage.read(
            user_id="USER-OTHER",
            storage_key=result.storage_key,
        )


def test_unsafe_storage_identifiers_are_rejected(
    tmp_path: Path,
) -> None:
    """Artifact identifiers cannot influence filesystem traversal."""

    storage = LocalArtifactStorage(
        tmp_path
    )

    with pytest.raises(
        ValueError,
        match="unsafe characters",
    ):
        storage.save(
            user_id="USER-001",
            cv_version_id="../escape",
            artifact_id="ART-001",
            artifact_format=CVArtifactFormat.DOCX,
            data=b"data",
        )