"""persist CV versions and artifacts

Revision ID: 8eb5336b0db8
Revises: f19c0a0d1c2b
Create Date: 2026-08-09 19:46:15.751816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8eb5336b0db8"
down_revision: str | Sequence[str] | None = "f19c0a0d1c2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cv_versions",
        sa.Column("cv_version_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("cv_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("parent_version_id", sa.String(length=64), nullable=True),
        sa.Column("source_document_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "structured_cv",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "applied_changes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('assembled', 'rendered', 'verified')",
            name=op.f("ck_cv_versions_status_valid"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_cv_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["cv_versions.cv_version_id"],
            name=op.f("fk_cv_versions_parent_version_id_cv_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["job_analysis_runs.thread_id"],
            name=op.f("fk_cv_versions_thread_id_job_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "source_document_id"],
            ["career_documents.user_id", "career_documents.document_id"],
            name="source_document_owner",
        ),
        sa.PrimaryKeyConstraint("cv_version_id", name=op.f("pk_cv_versions")),
        sa.UniqueConstraint(
            "user_id", "cv_id", "version_number", name="user_cv_version_number"
        ),
    )
    op.create_index(
        "ix_cv_versions_user_cv", "cv_versions", ["user_id", "cv_id"], unique=False
    )
    op.create_index(
        "ix_cv_versions_user_job", "cv_versions", ["user_id", "job_id"], unique=False
    )
    op.create_index(
        "ix_cv_versions_user_status", "cv_versions", ["user_id", "status"], unique=False
    )
    op.create_table(
        "cv_artifacts",
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("cv_version_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_format", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("sha256_hex", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column(
            "verification_notes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "artifact_format IN ('docx', 'pdf')",
            name=op.f("ck_cv_artifacts_artifact_format_valid"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('pending', 'verified', 'failed')",
            name=op.f("ck_cv_artifacts_verification_status_valid"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_cv_artifacts_size_bytes_positive")
        ),
        sa.ForeignKeyConstraint(
            ["cv_version_id"],
            ["cv_versions.cv_version_id"],
            name=op.f("fk_cv_artifacts_cv_version_id_cv_versions"),
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_cv_artifacts")),
        sa.UniqueConstraint(
            "cv_version_id", "artifact_format", name="version_artifact_format"
        ),
        sa.UniqueConstraint("storage_key", name="cv_artifact_storage_key_unique"),
    )
    op.create_index(
        "ix_cv_artifacts_version_format",
        "cv_artifacts",
        ["cv_version_id", "artifact_format"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cv_artifacts_version_format", table_name="cv_artifacts")
    op.drop_table("cv_artifacts")
    op.drop_index("ix_cv_versions_user_status", table_name="cv_versions")
    op.drop_index("ix_cv_versions_user_job", table_name="cv_versions")
    op.drop_index("ix_cv_versions_user_cv", table_name="cv_versions")
    op.drop_table("cv_versions")
    # ### end Alembic commands ###
