"""create career evidence table

Revision ID: ce2e57cff0a3
Revises:
Create Date: 2026-08-06 21:17:33.908264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce2e57cff0a3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_evidence",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column(
            "technologies",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "approved_claims",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "source_references",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "category IN ("
                "'project', "
                "'employment', "
                "'education', "
                "'certification', "
                "'achievement', "
                "'skill'"
                ")"
            ),
            name=op.f("ck_career_evidence_category_valid"),
        ),
        sa.CheckConstraint(
            (
                "verification_status IN ("
                "'pending', "
                "'approved', "
                "'rejected', "
                "'superseded'"
                ")"
            ),
            name=op.f("ck_career_evidence_verification_status_valid"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "evidence_id", name=op.f("pk_career_evidence")
        ),
    )
    op.create_index(
        "ix_career_evidence_user_status",
        "career_evidence",
        ["user_id", "verification_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_career_evidence_user_status", table_name="career_evidence")
    op.drop_table("career_evidence")
    # ### end Alembic commands ###
