"""persist CV evidence review workflow

Revision ID: f19c0a0d1c2b
Revises: ed59d77f31a9
Create Date: 2026-08-08 21:06:07.240529

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f19c0a0d1c2b"
down_revision: str | Sequence[str] | None = "ed59d77f31a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_documents",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("document_format", sa.String(length=16), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256_hex", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_format IN ('pdf', 'docx')",
            name=op.f("ck_career_documents_document_format_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded', 'extracted', 'quarantined')",
            name=op.f("ck_career_documents_status_valid"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0",
            name=op.f("ck_career_documents_size_bytes_positive"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "document_id",
            name=op.f("pk_career_documents"),
        ),
        sa.UniqueConstraint(
            "storage_key",
            name="storage_key_unique",
        ),
    )
    op.create_index(
        "ix_career_documents_user_sha256",
        "career_documents",
        ["user_id", "sha256_hex"],
        unique=False,
    )
    op.create_index(
        "ix_career_documents_user_status",
        "career_documents",
        ["user_id", "status"],
        unique=False,
    )

    op.create_table(
        "cv_evidence_review_runs",
        sa.Column("review_run_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "proposals",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "overlap_findings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "document_warnings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_result",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(status = 'completed' AND review_result IS NOT NULL) "
                "OR (status <> 'completed' AND review_result IS NULL)"
            ),
            name=op.f("ck_cv_evidence_review_runs_review_result_status_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_review', 'completed', 'invalid')",
            name=op.f("ck_cv_evidence_review_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "document_id"],
            [
                "career_documents.user_id",
                "career_documents.document_id",
            ],
            name="document_owner",
        ),
        sa.PrimaryKeyConstraint(
            "review_run_id",
            name=op.f("pk_cv_evidence_review_runs"),
        ),
    )
    op.create_index(
        "ix_cv_evidence_review_runs_user_document",
        "cv_evidence_review_runs",
        ["user_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_cv_evidence_review_runs_user_status",
        "cv_evidence_review_runs",
        ["user_id", "status"],
        unique=False,
    )

    op.create_table(
        "cv_evidence_review_history",
        sa.Column("review_id", sa.String(length=64), nullable=False),
        sa.Column("review_run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "decision_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "result_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_run_id"],
            ["cv_evidence_review_runs.review_run_id"],
            name=op.f(
                "fk_cv_evidence_review_history_review_run_id_cv_evidence_review_runs"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "review_id",
            name=op.f("pk_cv_evidence_review_history"),
        ),
        sa.UniqueConstraint(
            "review_run_id",
            "sequence_number",
            name="review_run_sequence",
        ),
    )
    op.create_index(
        "ix_cv_evidence_review_history_run_sequence",
        "cv_evidence_review_history",
        ["review_run_id", "sequence_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_cv_evidence_review_history_run_sequence",
        table_name="cv_evidence_review_history",
    )
    op.drop_table("cv_evidence_review_history")
    op.drop_index(
        "ix_cv_evidence_review_runs_user_status",
        table_name="cv_evidence_review_runs",
    )
    op.drop_index(
        "ix_cv_evidence_review_runs_user_document",
        table_name="cv_evidence_review_runs",
    )
    op.drop_table("cv_evidence_review_runs")
    op.drop_index(
        "ix_career_documents_user_status",
        table_name="career_documents",
    )
    op.drop_index(
        "ix_career_documents_user_sha256",
        table_name="career_documents",
    )
    op.drop_table("career_documents")
    # ### end Alembic commands ###
